{% set name = "nifti_clib" %}
{% set version = "3.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NIFTI-Imaging/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 868b611b5f8a3a73809436c9072db50db4975615905f0bd5fb7b1432e6d24b37
  # for local testing of the recipe use the following  
  #   -    git_url: /local/nifti_clib/

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    # If changing cmake version see:
    # https://github.com/conda-forge/cmake-feedstock/issues/106
    - cmake<3.13.4
    - {{ compiler('c') }}
    - help2man
  host:
    - zlib

test:
  commands:
    - test -f ${PREFIX}/include/nifti1.h
    - test -f ${PREFIX}/lib/libniftiio.a

about:
  home: https://github.com/NIFTI-Imaging/nifti_clib
  license: Public Domain
  license_family: PUBLIC-DOMAIN
  license_file: LICENSE
  summary: 'C library for IO with the nifti file format.'

extra:
  recipe-maintainers:
    - leej3
